[package]
rust-version.workspace = true
name = "sdkwork-routes-notes-http-auth"
version.workspace = true
edition.workspace = true


[lints]
workspace = true
[lib]
name = "sdkwork_routes_notes_http_auth"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
http.workspace = true
serde.workspace = true
sdkwork-notes-pages-service.workspace = true
sdkwork-web-core.workspace = true
sdkwork-web-axum.workspace = true
sdkwork-utils-rust.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde_json.workspace = true
