[package]
rust-version.workspace = true
name = "sdkwork-notes-pages-service"
version.workspace = true
edition.workspace = true


[lints]
workspace = true
[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
sdkwork-utils-rust.workspace = true
