[package]
rust-version.workspace = true
name = "sdkwork-routes-notes-app-api"
version.workspace = true
edition.workspace = true


[lints]
workspace = true
[lib]
name = "sdkwork_routes_notes_app_api"
path = "src/lib.rs"

[dependencies]
sdkwork-database-config = { workspace = true }
axum.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
sdkwork-notes-pages-service.workspace = true
sdkwork-routes-notes-http-auth.workspace = true
sdkwork-web-core.workspace = true
sdkwork-web-axum.workspace = true
sdkwork-utils-rust.workspace = true
sdkwork-iam-web-adapter.workspace = true
sqlx.workspace = true
tokio.workspace = true

[dev-dependencies]
async-trait.workspace = true
sdkwork-notes-pages-repository-sqlx.workspace = true
sdkwork-routes-notes-http-auth = { workspace = true }
sdkwork-iam-web-adapter.workspace = true
tower.workspace = true
